// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpWqxXBX0AD9Qj1irzFn1aYoYp1YY4f0I',
    appId: '1:1034179588846:web:62012213222bac2961f9ff',
    messagingSenderId: '1034179588846',
    projectId: 'soc-analyst-51da1',
    authDomain: 'soc-analyst-51da1.firebaseapp.com',
    storageBucket: 'soc-analyst-51da1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxhtFGuHB5M3Hg-jTH-DTJH7n1FbBXSw',
    appId: '1:1034179588846:android:a4b66ca4647c247561f9ff',
    messagingSenderId: '1034179588846',
    projectId: 'soc-analyst-51da1',
    storageBucket: 'soc-analyst-51da1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOP0-Rxm_164t0m-g_4_77YlZmGAxWWQc',
    appId: '1:1034179588846:ios:de833b04808bd62b61f9ff',
    messagingSenderId: '1034179588846',
    projectId: 'soc-analyst-51da1',
    storageBucket: 'soc-analyst-51da1.firebasestorage.app',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOP0-Rxm_164t0m-g_4_77YlZmGAxWWQc',
    appId: '1:1034179588846:ios:de833b04808bd62b61f9ff',
    messagingSenderId: '1034179588846',
    projectId: 'soc-analyst-51da1',
    storageBucket: 'soc-analyst-51da1.firebasestorage.app',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpWqxXBX0AD9Qj1irzFn1aYoYp1YY4f0I',
    appId: '1:1034179588846:web:10fd7dc82987ae7161f9ff',
    messagingSenderId: '1034179588846',
    projectId: 'soc-analyst-51da1',
    authDomain: 'soc-analyst-51da1.firebaseapp.com',
    storageBucket: 'soc-analyst-51da1.firebasestorage.app',
  );
}
